name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Extract version and build EXE
        shell: bash
        run: |
          version="${GITHUB_REF_NAME}"               # v0.8
          version_number="${version#v}"              # 0.8
          version_tag="${version_number/./p}"        # 0p8
          script_name="voxshare-gui_v${version_tag}.py"
          exe_name="voxshare_v${version_number}.exe"

          echo "SCRIPT_NAME=$script_name" >> $GITHUB_ENV
          echo "EXE_NAME=$exe_name" >> $GITHUB_ENV

          pyinstaller --onefile --noconsole --icon=Icons/logo32x32.ico --add-data "Icons/logo.png;images" "$script_name"
          mv "dist/${script_name%.py}.exe" "dist/$exe_name"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ env.EXE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

