name: Build and Release VoxShare

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Prepare variables
        run: |
          VERSION=${GITHUB_REF##*/}
          SCRIPT_NAME="voxshare-gui_${VERSION//./p}.py"
          EXE_NAME="voxshare_${VERSION}.exe"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "SCRIPT_NAME=$SCRIPT_NAME" >> $GITHUB_ENV
          echo "EXE_NAME=$EXE_NAME" >> $GITHUB_ENV

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --icon=Icons/logo32x32.ico --add-data "Icons/logo.png;images" "$SCRIPT_NAME"
          mv "dist/voxshare-gui_${{ env.VERSION//./p }}.exe" "dist/${{ env.EXE_NAME }}"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/${{ env.EXE_NAME }}
