name: Build and Release VoxShare

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Get version from tag
        id: get_version
        run: |
          version=${GITHUB_REF##*/}
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Build EXE
        run: |
          script_name="voxshare-gui_${{ env.VERSION//./p }}.py"
          pyinstaller --onefile --noconsole --icon=Icons/logo32x32.ico --add-data "logo.png;images" "$script_name"
          mv dist/voxshare-gui_${{ env.VERSION//./p }}.exe dist/voxshare_${{ env.VERSION }}.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/voxshare_${{ env.VERSION }}.exe
